### ISSUE TITLE
404 Not Error

### ISSUE THREAD

**Issue by ogzcode** [capjamesg/aurora#7]
### Bug

When the application first runs and goes to the home page, it gives this error and the files are not visible.

```
Traceback (most recent call last):
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\web.py", line 2688, in get
    self.absolute_path = self.validate_absolute_path(self.root, absolute_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\web.py", line 2900, in validate_absolute_path
    raise HTTPError(404)
tornado.web.HTTPError: HTTP 404: Not Found
```

```
if watch:
        from livereload import Server

        srv = Server()

        logging.disable(logging.INFO)

        print("Live reload mode enabled.\nWatching for changes...\n")
        print("View your site at \033[92mhttp://localhost:8000\033[0m")
        print("Press Ctrl+C to stop.")

        srv.watch(ROOT_DIR, lambda: main(deps=[srv.watcher.filepath]))
        srv.watch("./assets", lambda: copy_asset_to_site([srv.watcher.filepath]))
        srv.serve(root=SITE_DIR, liveport=35729, port=8000, debug=True)
```
        
I fixed it here so that the error appears and it also throws the following error from `venv` to the vs code console.

```
Traceback (most recent call last):
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\ioloop.py", line 937, in _run
    val = self.callback()
          ^^^^^^^^^^^^^^^
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\autoreload.py", line 183, in _reload_on_update
    _check_file(modify_times, path)
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\autoreload.py", line 198, in _check_file
    _reload()
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\autoreload.py", line 205, in _reload
    fn()
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\livereload\server.py", line 350, in <lambda>
    add_reload_hook(lambda: IOLoop.instance().close(all_fds=True))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 11\Desktop\aurora-example\venv\Lib\site-packages\tornado\platform\asyncio.py", line 153, in close
    self.asyncio_loop.close()
  File "C:\Python312\Lib\asyncio\selector_events.py", line 101, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
```

### Minimal Reproducible Example

I haven't written any code yet, I just downloaded the package and made `aurora serve`.

### Additional

`OS: Windows`
`Python 3.12.3`

**Comment by j1mc** [comment]
This is a late comment, but I note in the README that Aurora is not yet supported on Windows.
